apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-comment
  labels:
    app: comment-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-msa
  template:
    metadata:
      labels:
        app: comment-msa
    spec:
      containers:
      - name: comment-msa
<<<<<<< HEAD
        image: ${DOCKER_HUB_ID}/edu-msa-comment:latest        
=======
        image: nayoungjang/edu-msa-comment:latest
>>>>>>> 442861df274809019076682da12a9d0d01c50432
        imagePullPolicy: Always
        ports:
        - containerPort: 28083             
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-comment
  labels:
    app: comment-msa
spec:
  ports:
<<<<<<< HEAD
  - port: 28083
=======
  - nodePort: 30301
    port: 28083
>>>>>>> 442861df274809019076682da12a9d0d01c50432
    protocol: TCP
    targetPort: 28083
  selector:
    app: comment-msa
  type: ClusterIP

