apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-ui
  labels:
    app: ui-msa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-msa
  template:
    metadata:
      labels:
        app: ui-msa
    spec:
      containers:
      - name: ui-msa
        image: 45.248.73.57:5001/edu-msa-03/edu-msa-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 28080     
      imagePullSecrets:
         - name: edu-msa-secret-03  
      nodeSelector:
        kubernetes.io/hostname: playpark-caas-worker-3
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-ui
  labels:
    app: ui-msa  
spec:
  ports:
  - nodePort: 30003
    port: 28080
    protocol: TCP
    targetPort: 28080
  selector:
    app: ui-msa
  type: NodePort
